### ISSUE TITLE
Don't display "content" in widget when note has no content

### ISSUE THREAD

**Issue by martinkoutecky** [BijoySingh/Scarlet-Notes#109]
When a note has a title but no content, the widget displays the title in white and then as a second line in darker font the word "Content". This makes the note unnecessarily tall, and the word "Content" doesn't contribute any usefulness. It seems best to just remove it.

**Comment by BijoySingh** [comment]
Fixed as of 97e4adf18fe01152055d0a0379fcdd394987fb6c
