### ISSUE TITLE
Don't display archived notes in widget

### ISSUE THREAD

**Issue by martinkoutecky** [BijoySingh/Scarlet-Notes#110]
A note only disappears from the widget if it is put in trash. I would prefer to archive my notes, but this makes them stay in the widget, which then makes it cluttered. I think it is at least a sensible default to *not* display archived notes, or make it an option in the settings.

**Comment by BijoySingh** [comment]
Fixed in 97e4adf18fe01152055d0a0379fcdd394987fb6c
