### ISSUE TITLE
Render formatting in widget

### ISSUE THREAD

**Issue by martinkoutecky** [BijoySingh/Scarlet-Notes#111]
When a note contains some formatting (bold, italic, list), this formatting is displayed verbatim in the widget, but it is rendered properly in the main window (list of all notes) and when displaying the individual note.

**Comment by BijoySingh** [comment]
Resolved in 226422d2b209cb85bd26b3d18b51a828d851637c

**Comment by martinkoutecky** [comment]
@BijoySingh thanks for fixing this! However, now that I've got the update, I see that the note title size is larger in the widget than in the notes list, which is way too large for me. It causes me to see perhaps half the notes in the widget when compared to the previous version. Could you make the title smaller in the widget? I was forced to turn off markdown rendering in the widget for now.

Otherwise great tool! Thanks a lot!
