### ISSUE TITLE
Unchecked checkbox jumps across subheadings and separators

### ISSUE THREAD

**Issue by manasb** [BijoySingh/Scarlet-Notes#112]
I have a document with checklists under a few subheadings with dividing separators:

---
---

## Subheader1
[ ] test0
[ ] test1
[x] test2

---

## Subheader2
[ ] ~~test0~~
[x] test1
[x] test2

---
---

When I enable the checkmark on item Subheader1/test0, Subheader2/test0 jumps across from Subheader2 to Subheader1 and has to be manually moved back to Subheader2.

**Comment by BijoySingh** [comment]
Solved in 8d1af5bfe0d7470d9978c602da9e31ebe0af0f87

**Comment by manasb** [comment]
Thanks!
