### ISSUE TITLE
Broken link not fixable at this time

### ISSUE THREAD

**Issue by m1ck2** [BijoySingh/Scarlet-Notes#118]
Link is not server compatible at this stage and not repairable I was ignoring links connection attempts due to low power but on insistence of you I allowed connect but if this your game I will be playing much differently in future and no more bylink ✍️✍️✍️🤮

**Comment by BijoySingh** [comment]
Hi m1ck2,
I am not sure what you're talking about?

**Comment by m1ck2** [comment]
I need a 🚘or🚁

**Comment by Fs00** [comment]
Lol. It seems he typed using only keyboard suggestions :smile:
