### ISSUE TITLE
[BUG] [UI] Notebook notes count in home includes trash and archive

### ISSUE THREAD

**Issue by Fs00** [BijoySingh/Scarlet-Notes#119]
Notes count on notebooks in home screen is wrong: it includes also archived and deleted notes belonging to that notebook.
That's very confusing for a user which archives or deletes a note in a particular notebook, and then in home the counter looks like nothing has changed. But when you enter the notebook, you see that the action was successful and you realize that there's a mismatch between the count in the home and the effective content of that folder.

**Comment by BijoySingh** [comment]
Btw, @Fs00 I really appreciate the recent issues you added and the detail in them! Really made it easy reproducing them.

 If you are interested in connecting, feel free to mail with me on team.thecodershub@gmail.com. I'll be happy to give you a promo code for Scarlet Pro (or any other paid apps I work on https://play.google.com/store/apps/dev?id=8896637286724804826 here) too if you want.

**Comment by Fs00** [comment]
Many thanks! I've got many other bugs to report :wink:

**Comment by Fs00** [comment]
It appears that 1b99ef1 fixed it.
