### ISSUE TITLE
[UX] Various inconsistencies with notebooks

### ISSUE THREAD

**Issue by Fs00** [BijoySingh/Scarlet-Notes#121]
Using the app, I've found various UI/UX inconsistencies with notebooks that are listed below:
- when entering an empty folder, if you create a note using the "No notes" suggestion, the note is saved outside the selected folder
- the create folder button in the bottom bar should be hidden when you're inside a folder, since folders can't be nested. All the actions of the other buttons refers to the context of the actual folder, so keeping it when you navigate inside a folder is confusing
- when you delete a notebook, all the notes contained in it don't go to trash, but are moved in home! When a user deletes a folder, normally he/she expects that all of its content are moved to trash. If you want to keep that feature, I'd add another action called "Move content outside"
- when you delete a notebook, it doesn't go to trash - it vanishes. I suggest an alternative behavior: when the user deletes a notebook, all the notes inside of it _(not the archived ones, if you are in home, and viceversa if you are in archive)_ are moved to trash, so that the note structure is preserved in case the user wants to restore the notes inside

**Comment by BijoySingh** [comment]
I have started a project for tracking these: https://github.com/BijoySingh/Scarlet-Notes/projects/5
