### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by Hob111** [BijoySingh/Scarlet-Notes#125]
Apologies for the blank entry. See below.

**Comment by Hob111** [comment]
This is a great multi featured note app but seems to involve a very steep learning curve - for me at least!

Would it be possible to have:

1. A quick reference guide to the multitude of icons which are used? Some are very obvious and in common use. Others are more obscure.
2. A short user guide or help file for newbies?

Maybe these already exist, if so could someone point me at them please? If not it's maybe the sort of thing an experienced user could create?

Thanks

**Comment by BijoySingh** [comment]
Hi @Hob111,
That's a great idea, will incorporate it. For now you can do the following:

In the note creation view, click the bottom right (3 dots more icon), and then the help icon.

**Comment by HarryHeights** [comment]
I think a FAQs document would be a good thing to have. It wasn't easy for me using the app at first. At a point, I stopped using it. But, I went back to it deciding that an app shouldn't be smarter than me. I'm quite conversant with the app now.
I could help create the FAQs document @BijoySingh

**Comment by Hob111** [comment]
Hi @HarryHeights,
I'd be very happy if you'd take on the creation of a FAQ, I've stopped using the app as you did. Over to you @BijoySingh?

**Comment by BijoySingh** [comment]
The FAQ definitely is a good idea. I am happy to setup the initial framework for it, add some basic stuff and then you guys can add to it / it could grow organically.

It would help to know questions you faced when using the app.

**Comment by BijoySingh** [comment]
Ok, so I created the gh pages branch (`gh-pages`), where in `<ROOT>/faq/README.md` lies the frequently asked questions. I will create a view in the app, where the user can see this FAQ page.

**Comment by HarryHeights** [comment]
That's great @BijoySingh . I'm mostly good at content creation. I'll create the FAQs and leave implementation on the app to you.
