### ISSUE TITLE
Notfication button in editor

### ISSUE THREAD

**Issue by sandoxy** [BijoySingh/Scarlet-Notes#128]
It would be great, if one could set notifications or pin the edited note to android notifications menu directly from the note editor. 

Thanks.

**Comment by BijoySingh** [comment]
You can add it to the notifications from the note viewer. Yes, it is not the editor, but since you would be quitting the app anyways, it shouldn't be too much change in experience to go back and adding a notification. It also allows to follow the philosophy of no note actions in the editor page.
