### ISSUE TITLE
Widget scrolling conflicts with home screen gestures

### ISSUE THREAD

**Issue by iammexan** [BijoySingh/Scarlet-Notes#132]
Firstly, I'd say this is the most beautiful and feature rich note-taking app I've seen. I'm migrating my notes here but some problems and lack of features are bothering me. I'll report them one at a time. 

For now, the most annoying bug I found is that while I scroll a long note from the widget in home screen, the scrolling up or down both trigger my preset home screen gestures. For example my notification panel opens down when I _scroll down_ on home screen, now when I'm scrolling(_down_) the note in the widget from home, the note scrolls down alright but just as I lift my finger my notification panel opens. Similar thing happens for scrolling up. 

I've tried other apps' widgets, the scrolling doesn't conflict with my home screen in them.

Edit: Sorry for not checking it earlier...the multi-note displaying widget doesn't have this problem, __only the single note displaying widget__ has.

**Comment by BijoySingh** [comment]
Thanks, I kinda suspected the Edit. Android is kinda poor at this that only a list view has proper support for preventing nested scroll on the homescreen, while a normal text layout which a single note widget is, is not great. Closing the issue, as it is not easy to solve.
