### ISSUE TITLE
Delete note(s) directly without moving it to trash

### ISSUE THREAD

**Issue by AndhikaWB** [BijoySingh/Scarlet-Notes#134]
Please add option to replace 'Move to Trash' with 'Delete permanently' when enabled on settings.

Some people like me have many important notes and it's quite annoying if I need to delete the notes twice (from Home and then Trash).

**Comment by BijoySingh** [comment]
You can scroll down on the note options sheet and find delete permanently. I don't think it's a great experience to have the option for the delete button to delete permanently by default even as an option.
