### ISSUE TITLE
Question: Scarlet Web Open Source / Self-Hosted

### ISSUE THREAD

**Issue by tadly** [BijoySingh/Scarlet-Notes#137]
As there's no dedicated repository for it, I'll ask here.

Are there plans on making scarlet web open source / self hostable once it reaches RC or stable?
Finding a self hosted google keep alternative is a tough nut to crack and scralet might just be the only real solution.

**Comment by r0bbie** [comment]
Just to add that I'd also love to see this. Trying out various open source note-taking solution on Android, and Scarlet Notes seems by far the best! Really impressed and I've immediately moved to it for mobile notes.

Unfortunately I'm having to use a completely different note-taking solution on desktop, with no syncing between the two. Fingers crossed for a desktop or (self-hostable) web-based version of Scarlet Notes in future! Looking into using the "Folder Sync" feature with Nextcloud just as a backup in the meantime.

**Comment by BijoySingh** [comment]
So I do have something in the works... However I am really struggling with time.
Also with WebDAV coming (which is the next thing i want to complete) that would work probably first with that. 

I will close this Issue for now. 

![Scarlet-Desktop-Preview](https://user-images.githubusercontent.com/5511083/67133241-e0b08800-f203-11e9-8311-c6f18bfab011.PNG)

**Comment by ParadoxicalNerd** [comment]
Hey, has there been any updates regarding this?
