### ISSUE TITLE
[BUG] [UI] Multiline options descriptions have wrong alignment

### ISSUE THREAD

**Issue by Fs00** [BijoySingh/Scarlet-Notes#143]
As it is shown in the screenshot below, when option description takes more than one line, the text becomes misaligned and seems to ignore icon right padding (it is more noticeable in other UI languages).
I've tried experimenting with the layout of LithoOptionBottomSheet and I couldn't find a solution. I suppose that the problem may be related to the behavior of Android TextView described in [this StackOverflow thread](https://stackoverflow.com/questions/7439748/why-is-wrap-content-in-multiple-line-textview-filling-parent).
![scarletbug](https://user-images.githubusercontent.com/30041551/63521931-aecac000-c4f7-11e9-9a2a-5ef3c96a019f.png)

**Comment by BijoySingh** [comment]
Yeah it seems to be a weird rendering issue. Given there's little I can do here, I am gonna close this. 

Thanks for flagging it, I didn't even realise this! :D

**Comment by Fs00** [comment]
Ok. Please also have a look at my recent PRs, they don't introduce big changes.
