### ISSUE TITLE
Dots of bullet points are not aligned vertically with text

### ISSUE THREAD

**Issue by KevCui** [BijoySingh/Scarlet-Notes#23]
The dots look like a bit weird. They're not aligned vertically with text.

![screenshot_20171218-230653__01](https://user-images.githubusercontent.com/14293537/34130544-881ec154-e448-11e7-9065-ae79096d5714.jpg)

Very minor ui stuff, sorry for my OCD...

**Comment by BijoySingh** [comment]
Oh no, I understand :) 
Sadly I am using a library https://github.com/noties/Markwon to do this. And I am recently finding a bunch of issues with it. Will make Markdown disabled by default and opt-in till these issues are resolved. 
(Same applies to the other issue #22)

**Comment by Ezelty** [comment]
I'd like to add that the bullet don't always have the same size. Most of the time the last bullet of the list is smaller than the other ones.

**Comment by SitiSchu** [comment]
@Ezelty I found this issue too. Would it make sense to create a separate issue ?

**Comment by BijoySingh** [comment]
Scarlet doesnt have bullet support anymore. Closing this
