### ISSUE TITLE
[Feature Request] Button to undo deletion or archiviation

### ISSUE THREAD

**Issue by Jiack214** [BijoySingh/Scarlet-Notes#53]
Maybe thorugh a [snackbar](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsZV9TS3lTVHFzRUE/components-snackbar-usage-fabdo-005.webm).

**Comment by BijoySingh** [comment]
Resolved in 89e34d790a41b691e7da38f89cb7136d0641bf23
