### ISSUE TITLE
Security of locked notes

### ISSUE THREAD

**Issue by Namnodorel** [BijoySingh/Scarlet-Notes#64]
Are locked notes actually encrypted properly? Because the ability to search through the full texts of locked notes even without entering the key suggests otherwise.

If you want to really lock notes, I suggest to actually encrypt them. Otherwise this feature is just a fancy UI that won't hold anyone apart from not-so-techies back from accessing locked notes in cleartext. 
With completely encrypted notes, those either wouldn't be searchable or you'd have to enter your PIN to also search through those as well.

**Comment by BijoySingh** [comment]
A simpler way to go about preventing at least a brute force way of finding the text is to simply make locked notes not searchable. 

I'll add that :)

**Comment by BijoySingh** [comment]
Closing as the search is fixed.

**Comment by Namnodorel** [comment]
Sorry, just now noticed that you answered this.

> Now no matter what your password is, it will be very easy to crack if the text itself is very simple.

Why is that? Wouldn't it be easier to crack if there was more text encrypted with the same key? (Well, with a bad encryption algorithm anyways. Anything up-to-date should be secure no matter the text length) Or do you mean a simple/short password is easy to crack?
