### ISSUE TITLE
AWESOME LOGO DESIGN FREE FOR YOU 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [BijoySingh/Scarlet-Notes#74]
Hello, @BijoySinghI want to contribute in "Scarlet-Notes" so i  want to designed a new logo for "Scarlet-Notes" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by TacoTheDank** [comment]
stop

**Comment by abdulmalikkhan655** [comment]
scamer

**Comment by BijoySingh** [comment]
Thanks @abdulmalikkhan655 but we have an in-house designer who is working on this already :)

**Comment by TacoTheDank** [comment]
@BijoySingh dont worry, hes mad at me for calling out his stealing icons from flaticons and passing them off as his own
