### ISSUE TITLE
Note deletion needs a dialog and feedback

### ISSUE THREAD

**Issue by faissaloo** [BijoySingh/Scarlet-Notes#79]
It's way too easy for me to accidentally delete an important note, I don't even get any feedback after deleting which is bad UX.  
I suggest a confirmation dialog and a toast after deletion.

**Comment by BijoySingh** [comment]
Thanks @faissaloo for this, dialog is probably an overkill, as it's still recoverable from Trash. 
A toast, surely. :)

**Comment by BijoySingh** [comment]
Resolved in 89e34d790a41b691e7da38f89cb7136d0641bf23
