### ISSUE TITLE
Respect 24H time format

### ISSUE THREAD

**Issue by gaydenko** [BijoySingh/Scarlet-Notes#85]
Hi!

6.1.0-pro on Android is in use. I live in one of the countries knowing nothing about AM/PM time format. Also appropriate Android (on Android 7.1.1 and 8.0 devices) settings are selected (that is both language+input and 24H time format). The settings are not respected by the Scarlet Notes.

**Comment by mnsc** [comment]
This is a dealbreaker for me! Whats extra confusing is that AM/PM translates to my language (swedish) and the formatting is dd:dd. So I get "01:01 em".
