### ISSUE TITLE
[Feature Request] Reminders based on time

### ISSUE THREAD

**Issue by Jiack214** [BijoySingh/Scarlet-Notes#9]
I would like to have an option to set reminder of a note at a specific time.

**Comment by BijoySingh** [comment]
Hi @Jiack214 thanks for the suggestion. Will consider it in future :)

**Comment by 4ut0-M-4t** [comment]
@BijoySingh, could you provide some informative feedback when closing issues, please? Even a simple `[WONTFIX]` label would do.
