### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by quantizzed** [BijoySingh/Scarlet-Notes#90]
Hi!
The F-Droid version has not been updated for 4 months and is currently stuck on v. 4.5.4. Is it going to be updated?

**Comment by lionirdeadman** [comment]
Still no update.. @BijoySingh? Anything to tell us?

**Comment by BijoySingh** [comment]
Merging with #1 as it has the right people. Something seem to have broken as I have a release which wasnt picked up by Fdroid.
