### ISSUE TITLE
F-Droid version not updated to 5.9.7

### ISSUE THREAD

**Issue by ghost** [BijoySingh/Scarlet-Notes#98]
The F-Droid version of the app is still 4.5.4, not 5.9.7. I'm not sure what could be causing this, but probably something in the versioning.

**Comment by Namnodorel** [comment]
It's updated now.

**Comment by quantizzed** [comment]
@BijoySingh thanks,
what about updating to the current Play Store version 6.6.2?

**Comment by BijoySingh** [comment]
Yes I have created a new release for 6.6.10. hopefully FDroid will pick it up soon. I'll follow up if that doesn't happen. :)

**Comment by quantizzed** [comment]
@BijoySingh 
6.6.2 has not arrived in F-Droid yet... still stuck at 5.9.7.

**Comment by BijoySingh** [comment]
I got some input from folks in FDroid. Made some code changes and created a 6.6.3 release. Let's see if this works. I'll wait for a day and create an issue on FDroid if it doesnt work
