### ISSUE TITLE
Wrong app name when downloaded from FDroid

### ISSUE THREAD

**Issue by madduck** [BijoySingh/Scarlet-Notes#99]
I've downloaded the app from F-Droid, and after the most recent update, it was renamed from "Material Notes" to "Scarlet FDroid". I think you wanted "Scarlet Notes", right?
![Screenshot of app icon](https://user-images.githubusercontent.com/195073/48923015-a5cca400-ef0f-11e8-8106-e7d63a1991d7.jpg)

**Comment by BijoySingh** [comment]
Actually this was intentional. But I am renaming it to "Scarlet Notes FD"
